steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/learners-codetree/my-cloudrun-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/learners-codetree/my-cloudrun-project:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'my-cloudrun-project', '--region=us-central1', '--platform=managed', '--image=gcr.io/${PROJECT_ID}/learners-codetree/my-cloudrun-project:$SHORT_SHA']
