steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/learners-codetree/my-cloudrun-project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/${PROJECT_ID}/learners-codetree/my-cloudrun-project:$SHORT_SHA', '.']
